### ISSUE TITLE
Anomaly detected during compilation

### ISSUE THREAD

**Issue by rmatthes** [UniMath/TypeTheory#182]
After compiling and installing the current UniMath library and installing it, I get the following with Debian 9 (the current version is Debian 10):

```> make
COQC TypeTheory/Initiality/InterpretationLemmas.v
Finished transaction in 6.397 secs (6.372u,0.019s) (successful)
Finished transaction in 3.817 secs (3.774u,0.039s) (successful)
File "./TypeTheory/Initiality/InterpretationLemmas.v", line 387, characters 2-11:
Error:
Anomaly
"File "interp/impargs.ml", line 388, characters 15-21: Assertion failed."
Please report at http://coq.inria.fr/bugs/.

build/CoqMakefile.make:715: recipe for target 'TypeTheory/Initiality/InterpretationLemmas.vo' failed
make[1]: *** [TypeTheory/Initiality/InterpretationLemmas.vo] Error 129
build/CoqMakefile.make:338: recipe for target 'all' failed
make: *** [all] Error 2
```

Can someone please confirm this with their proper installation?

Ralph

**Comment by benediktahrens** [comment]
I have just started a build on Travis, let’s see how that works: https://travis-ci.org/github/UniMath/TypeTheory/builds/703124255

**Comment by benediktahrens** [comment]
The Travis build shows the same error. @peterlefanulumsdaine , @mortberg , could you take a look?

**Comment by benediktahrens** [comment]
@rmatthes thanks for reporting this error!

**Comment by peterlefanulumsdaine** [comment]
@benediktahrens I’ll have a look at this today.

**Comment by peterlefanulumsdaine** [comment]
Oops, fixed in the wrong branch.  Will rebase the fix to master.

**Comment by peterlefanulumsdaine** [comment]
In any case: it seems like this is probably a Coq regression, reported at https://github.com/coq/coq/issues/12895.   In 8eb4d78 I’ve added a workaround for now, plus a note to revert it once the Coq bug is fixed.
