### ISSUE TITLE
Build system (opam) seems to require changes

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/TypeTheory#184]
Our travis build system uses opam, which seems to require changes to the setup. 

The complete log is here: https://api.travis-ci.org/v3/job/657119034/log.txt

@peterlefanulumsdaine @DanGrayson : would you be willing to investigate?

(The same problem affects UniMath/largecatmodules.)

**Comment by DanGrayson** [comment]
One complication also is that we use a docker image.

I've thinking we should switch from travis to github actions.  Perhaps now is an opportune time.  Meanwhile, I'll try to see what the problem is.

**Comment by DanGrayson** [comment]
Benedikt, was that build resulting from a pull request?  If so, which one?

**Comment by benediktahrens** [comment]
> Benedikt, was that build resulting from a pull request? If so, which one?

No, I saw this when triggering a rebuild of the master branch, to check if the current master still works with current UniMath/UniMath. And it does, luckily, just travis needed fixing.

**Comment by peterlefanulumsdaine** [comment]
Thanks both for dealing with this!
