### ISSUE TITLE
Reorganise library structure: consistently use topic-based packages, not project-based?

### ISSUE THREAD

**Issue by peterlefanulumsdaine** [UniMath/TypeTheory#205]
Several times recently I’ve found the current organisation of the library causing obstacles in development/refactoring; I think it’s slightly overdue for a bit of larger-scale reorganisation.

Currently, the grouping of files into packages is rather ad hoc, following several different ideas.  In particular, several packages correspond to particular research projects/papers, or at least started out that way.  A typical example of the tensions this causes:  The `ALV1` package contains the definition and some core development of split type-categories.  This gets imported, and further developed, in several other packages — at least `Initiality`, `ALV2`, and `OtherDefs`.  These each import it separately, so there’s a fair bit of near-duplicated material on split type-cats, which it would be good to consolidate.  But where should it get consolidated?  The natural place would be in the same file (or at least the same package) as the core development of split type-cats.  But that conflicts with the current naming scheme and documentation, which suggests that `ALV1` is meant to contain the material of the paper Ahrens–Lumsdaine–Voevodsky 2017.

**Generally: project-based packages conflict badly with other organisational demands**.  Organising packages by topic (like some of the present packages, and like all/most of `UniMath`) works much better.  The main benefit of project-based packages is that they help papers based on contributions to this library to showcase their contributions.  But that can be alternately accomplished by files like those in the `Articles` package, which summarise a contribution without making demands on the overall organisation.

So, briefly, I propose:

- the packages that are project-based should be dissolved, and reorganised into more consistently topic-based packages;
- the topic-based structure may also be reorganised to better fit the current state of the material;
- projects whose packages are dissolved should (either now or later) get files in the `Article` package.

Figuring out the full details is I think best done by trying it out and making a draft PR — it’s difficult to foresee exactly how the reorganisation will work — and I plan to take a crack at that soon.  **This issue is just to float the idea initially, and get advance input from other contributors** — do others agree this sounds good, or at least potentially so (pending a concrete draft PR)?  And are there other large-scale considerations I haven’t mentioned here, that should be kept in mind for the reorganisation?

**Comment by benediktahrens** [comment]
I agree. I am not sure what a good topic-based organization would be. One option would be having one package per categorical structure, and one per map/equivalence, for those of ALV1 and ALV2.

**Comment by peterlefanulumsdaine** [comment]
> One option would be having one package per categorical structure, and one per map/equivalence, for those of ALV1 and ALV2.

Right — something like that was my first thought.  I think *entirely* following that would make the organisation too flat — many packages with just one or two files.  So I’m thinking of something like: Individual packages for the structures that are more thoroughly developed (at least type-cats, CwF’s, C-systems, B-systems, comprehension categories), and for maps between them, but then retaining the current `OtherDefs` package for structures that aren’t developed in detail.

**Comment by benediktahrens** [comment]
Sounds good!
