### ISSUE TITLE
File `Bsystems/lBsystems_work` unlisted, stale, and very unclear status — salvage, delete, …?

### ISSUE THREAD

**Issue by peterlefanulumsdaine** [UniMath/TypeTheory#213]
FAO @rmatthes : I was just checking the repo for any .v-files not listed in packages (at the request of @benediktahrens), and found there is one unlisted file, `TypeTheory/Bsystems/lBsystems_work.`  It seems to be a code fragment without any context; it was only touched once, in July 2017, when @rmatthes initialised the `Bsystems` package in commit af46fa33 with message:

    very light modification of Vladimir Voevodsky's implementation of B-systems
    
    just to ensure that it compiles within the TypeTheory repository
    the file lBsystems_work.v does not compile and is therefore not mentioned in the file list
    (anyway, its contents has an unclear status)

Having dead code in the development is bad, so if nothing in this file is still wanted, then I suggest we delete it — it clearly has historical interest, but anyone who is interested in seeing VV’s original work should be looking back to the original version of the package anyway.  Or if there’s something in that that we genuinely still want in future, then could someone clean up this file to get it compiling (or at least as some of it), and add it to the package list so it doesn’t stale further?

**Comment by rmatthes** [comment]
@peterlefanulumsdaine : Without consulting my handwritten notes from that time and maybe my email exchange with Vladimir, I cannot dig out a potential justification for keeping this code. So, I approve your suggestion.

**Comment by m-lindgren** [comment]
Closing this since this file was removed with PR #228. The contents of the file will still be available in the UniMath/TypeTheory git repository here: [lBsystems_work.v](https://github.com/UniMath/TypeTheory/blob/71a4afea16f089f2d0c62d0afc5fdbfee9fb032a/TypeTheory/Bsystems/lBsystems_work.v)
