### ISSUE TITLE
Build fails with Coq 8.16.0

### ISSUE THREAD

**Issue by m-lindgren** [UniMath/TypeTheory#230]
There's an error when building TypeTheory with Coq 8.16.0. The error message is:
```coq
File "./TypeTheory/TypeTheory/Auxiliary/SetsAndPresheaves.v", line 117, characters 8-16:
Error:
In environment
C : category
F : preShv C
c : C
A : F c
c' : C
f : C ⟦ c', c ⟧
The term "# (F : C^op ⟶ HSET_univalent_category) f A" has type
 "pr1hSet (F c')" while it is expected to have type
"pr1hSet (?F ?c)".
```
I remeber encountering this problem a couple of months ago maybe, so I don't think it's a recent change that caused it. I took a look at the lemma in [SetsAndPresheaves.v](https://github.com/UniMath/TypeTheory/blob/45a6ed37c58bd8df882c9d124e94d04a8b2a2526/TypeTheory/Auxiliary/SetsAndPresheaves.v#L117) that fails but I couldn't make heads or tails of what's causing the error.

It fails on this version of Coq:
```bash
$ coqc --version
The Coq Proof Assistant, version 8.16.0
compiled with OCaml 4.13.1
```
and I verified that TypeTheory compiles with the following versions: ` 8.13.2`, `8.14.0`, `8.14.1`, `8.15.0`, `8.15.1`, `8.15.2`.

**Comment by benediktahrens** [comment]
Thanks for reporting this - I'll take a look.

It would be great if the Coq developers could check not just UniMath/UniMath, but also the satellite repositories. Considering the compile time of UniMath/UniMath, that might be too much to ask, though.

**Comment by benediktahrens** [comment]
In general, the problem that this code has to cope with is that certain coercions need to be triggered to make expressions well-typed. For instance, if `F : presheaf C`, then `F` is first of all an object in a category. By *simplifying*, `F` becomes a functor that can be applied to an argument, but Coq has to be told to do that simplification. 

@mortberg (I believe) introduced notation (see `$nt` and similar above in the same file) within which the coercions are encapsulated. Possibly Coq 8.16 handles these notations differently from previous versions?

**Comment by benediktahrens** [comment]
@m-lindgren : could we add a job to UniMath CI that tries building TypeTheory with Coq dev? It would be good to see if the situation has changed again, or is the same compared to 8.16.

**Comment by m-lindgren** [comment]
Absolutely, that's a good idea. I'll take a look at updating #231 first.

**Comment by m-lindgren** [comment]
Completed with #231.
